### ISSUE TITLE
Implement Textured Area Lights

### ISSUE THREAD

**Issue by marklundin** [playcanvas/engine#4320]
This ticket is a request for comments/progress tracker for adding **textured area lights** as an extension to the current LTC implementation.

[![image](https://user-images.githubusercontent.com/430764/173038301-5b739e1b-1cdd-468f-a0f9-b5eba48a1be3.png)](https://launch.playcanvas.com/1441929?use_local_engine=https://localhost:disable_engine)

**[DEMO](https://launch.playcanvas.com/1441929?use_local_engine=https://localhost:disable_engine)**

The above example includes an custom version of the engine (v1.54) that implements textured area lights using the current LTC shader chunks. It's using the cookie texture slot on the lighting system as the light source. Works with diffuse/specular/CC.

The blurriness/roughness is an approximation of a gaussian kernel that uses weighted samples of the mip-chain. This appears to be a better quality blur than [many other approaches](https://www.shadertoy.com/view/ssfSz2) (especially at higher blurriness levels) but is cheaper to compute  than most solutions of a [similar quality](https://www.shadertoy.com/view/XdfGDH). The cost is bound to the texture resolution (1k is 10 taps) and independent of the blur strength.

**Tasks:**
- [x] Update Standard Material + shader chunks
- [ ] Integrate with clustered lighting.

**Optional:**
- [ ] Implement a mipmap-less approach similar to https://github.com/playcanvas/engine/pull/3783 by @slimbuck may be suitable
- [ ] Allow lower quality/cheaper solution using 2 taps of the mip-chain

**Open Questions:**
1. Should the textured area lights use the cookie texture slot or a dedicated one. The semantics are different but there may also be some practical issues if one light has a cookie and another is a textured area light. This will also have implications for the cookie atlas in clustered lighting.
2. Is it preferable to pre-compute a mipmap-less texture in a similar way to https://github.com/playcanvas/engine/pull/3783. This may not always be required if using dynamic/video textures for example but for static ones, this may be beneficial

**Related PRs**
[Clustered Area Lights](https://github.com/playcanvas/engine/pull/3691)
[Clustered Lights](https://github.com/playcanvas/engine/issues/3522) 
[mipmap-less environment lighting](https://github.com/playcanvas/engine/pull/3783) 

Any feedback welcome @mvaligursky @slimbuck @willeastcott

**Comment by mvaligursky** [comment]
Fantastic work so far! 

- Cookie slots are rarely used, and personally I think using them for area lights cookie texture is a perfect solution.
- I think we'll need to implement a mipmap-less solution. This is definitely needed for clustered lights, where cookie textures are stored in an atlas.

Perhaps it could work like this:
- a cookie texture on an area light would be expected to be a normal texture / movie texture.
- internally, after the lights are culled, for visible area lights we'd generate a mipmap-less texture (result texture stored on a light, some private variable). Perhaps this could be handled similarly to how lights render shadows. By default it would generate mipmap-less once, but a property could be set to do it every-frame or this-frame (see SHADOWUPDATE_THISFRAME for example), giving user the control over the cost (for example every 10th frame).
- when the area light is used for rendering, it would use the mipmap-less texture.
- if clustered lighting is used, this mipmap-less texture would be then copied to the atlas.

I think it would be ok if this was done only for the clustered lights, saving having to do this for normal lighting as well - as this will get deprecated in not too distant future most likely.

**Comment by slimbuck** [comment]
This is fricken amazing! 🥹

Do you have any idea what might be causing the spikes on the ministats GPU plot?

<img width="1366" alt="Screenshot 2022-06-10 at 17 50 11" src="https://user-images.githubusercontent.com/11276292/173114468-9d440e9d-700e-4f91-8af6-2acb2858b13d.png">

**Comment by marklundin** [comment]
Will take a look @slimbuck, but it could well be the video texture upload which is happening outside the update loop

**Comment by marklundin** [comment]
I'm not seeing the same spikes on my machine @slimbuck but I've disabled the video texture upload regardless

**Comment by mvaligursky** [comment]
I think those spikes are caused by something (likely the GPU) taking longer than one frame, so on occasions a frame is skipped. Probably nothing to worry about at this stage.

**Comment by mvaligursky** [comment]
Just an update - in the engine 1.55 https://github.com/playcanvas/engine/releases/tag/v1.55.0 we've enabled the clustered lighting as the default lighting solution.

**Comment by marklundin** [comment]
That's great to hear @mvaligursky. I've not managed to integrate with the clustered lighting as yet as I've not had the time. It requires a bit of thought on the atlas texture fetches and sampling the mips without any bleeding

**Comment by SaadHaider7** [comment]
Hi, is textured area ligths in the roadmap?

**Comment by mvaligursky** [comment]
Not for the short-term.
